name: Upload to Tencent COS
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cn
        uses: actions/checkout@v2
        with:
          ref: cn

      - name: Clear COS
        uses: Bluefissure/tencent-cos-action@v0.1.1
        with:
          args: delete -r -f /
          secret_id: ${{ secrets.SECRET_ID }}
          secret_key: ${{ secrets.SECRET_KEY }}
          bucket: ${{ secrets.BUCKET }}
          region: ${{ secrets.REGION }}

      - name: Upload COS
        uses: Bluefissure/tencent-cos-action@v0.1.1
        with:
          args: upload -r ./plugins /plugins && upload ./pluginmaster.json /
          secret_id: ${{ secrets.SECRET_ID }}
          secret_key: ${{ secrets.SECRET_KEY }}
          bucket: ${{ secrets.BUCKET }}
          region: ${{ secrets.REGION }}
          accelerate: true
