name: Upload to Amazon S3
on:
  workflow_run:
    workflows: ["Regenerate PluginMaster"]
    branches: [cn-api5]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cn-api5
        uses: actions/checkout@v2
        with:
          ref: cn-api5
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --exclude '.git/*' --exclude '.github/*' --follow-symlinks --delete --size-only
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          DEST_DIR: 'cn-api5'
